#!/bin/bash

alphabet="A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
ua="Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0"
ualist=useragentlist.txt
basedir="http://fr.artprice.com/"
artistsdir="${basedir}artistes/directory/"
sample='francois-boucher'
tmpfile=/tmp/aspirateur.$$
idx=artists

test -s $idx && mv $idx $idx.`date +%s`

for first in $alphabet
do
    for second in $alphabet
    do
	letterdir="${artistsdir}$first/$second"
	pagenum=1
	while :
	do
	    stepdir="${letterdir}?page=$pagenum"
	    echo -n "fetching [$first/$second/$pagenum] "
	    pagenum=`expr $pagenum + 1`
	    if test -f "$ualist"; then
		tot=`awk 'BEG{cnt=0}{cnt=cnt+1}END{print cnt}' "$ualist"`
		rand=$RANDOM   #REQUIRES bash / sh-uncompliant!
		if test $rand -lt $tot; then
		    row=`expr $tot % $rand`
		else
		    row=`expr $rand % $tot`
		fi
		ua=`awk "BEG{cnt=0}{cnt=cnt+1;if (cnt == $row){print; exit;}}" "$ualist"`
	    fi
	    wget="`which wget` -q -U '$ua'"
	    $wget "$stepdir" -O $tmpfile
	    if test -s $tmpfile; then
		if ! grep -v $sample $tmpfile \
		    | grep 'href="/artiste/' >/dev/null; then
		    echo "Does not exist, skipping"
		    break
		else
		    echo OK
		fi
	    else
		echo "KO, skipping"
		continue
	    fi
	    grep 'href="/artiste/' $tmpfile \
		| sed 's|.*href="/artiste/\([0-9]*\)/\([^"]*\).*|\1 \2|' \
		| while read id ref
		do
		    echo "$id,$ref"
		done >>$idx
	done
    done
done

rm -f $tmpfile

exit 0
